import { useState } from 'react'
import { AlertTriangle, CheckCircle2, Flag, LockKeyhole, Users } from 'lucide-react'
import { issues } from './data'

export default function AdminPortal(){
 const [loggedIn,setLoggedIn]=useState(()=>sessionStorage.getItem('nv-admin')==='true'),[username,setUsername]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState('')
 const login=(event:React.FormEvent)=>{event.preventDefault();if(username==='admin'&&password==='admin123'){sessionStorage.setItem('nv-admin','true');setLoggedIn(true)}else setError('Incorrect username or password.')}
 if(!loggedIn)return <main className="admin-login-page"><form className="admin-login-card" onSubmit={login}><img src="/nagorik-voice-logo.png" alt="Nagorik Voice"/><LockKeyhole/><h1>Admin Panel Login</h1><p>Use your authorised administrator account.</p><label>Username<input autoComplete="username" value={username} onChange={e=>setUsername(e.target.value)} placeholder="Username"/></label><label>Password<input autoComplete="current-password" type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password"/></label>{error&&<p className="login-error">{error}</p>}<button className="primary">Login</button><small>Demo credentials: admin / admin123</small></form></main>
 return <main className="admin-portal"><header><img src="/nagorik-voice-logo.png" alt="Nagorik Voice"/><button className="outline" onClick={()=>{sessionStorage.removeItem('nv-admin');setLoggedIn(false)}}>Log out</button></header><section><span className="eyebrow">PLATFORM CONTROL</span><h1>Admin overview</h1><p>Monitor community activity, moderation and platform health.</p><div className="dashboard-stats"><Card icon={Users} value="8,492" label="Total users"/><Card icon={Flag} value={issues.length.toString()} label="Total issues"/><Card icon={CheckCircle2} value="327" label="Resolved"/><Card icon={AlertTriangle} value="14" label="Moderation queue"/></div><div className="panel"><h2>Recent reports</h2>{issues.map(issue=><div className="admin-report" key={issue.id}><img src={issue.image}/><div><b>{issue.title}</b><span>{issue.location}</span></div><em>{issue.status}</em></div>)}</div></section></main>
}
function Card({icon:Icon,value,label}:{icon:any;value:string;label:string}){return <div className="dash-stat"><span className="blue"><Icon/></span><div><b>{value}</b><p>{label}</p></div></div>}
