import { useMemo, useState } from 'react'
import { Ban, CheckCircle2, ChevronRight, FileText, LayoutDashboard, LogOut, MapPin, Send, Settings, Tags, Trash2, Users, X } from 'lucide-react'
import { categories, type Issue } from './data'

type View='dashboard'|'posts'|'users'|'categories'
type Props={items:Issue[];forward:(issue:Issue)=>Promise<void>;remove:(issue:Issue)=>Promise<void>;ban:(issue:Issue)=>Promise<void>;updateStatus:(issue:Issue,status:Issue['status'])=>Promise<void>;logout:()=>Promise<void>}
const status=(issue:Issue)=>`status ${issue.status.toLowerCase().replaceAll(' ','-')}`

export default function CCExperience({items,forward,remove,ban,updateStatus,logout}:Props){
 const [view,setView]=useState<View>('dashboard'),[category,setCategory]=useState('All issues'),[modal,setModal]=useState<Issue|null>(null)
 const users=useMemo(()=>Object.values(items.reduce<Record<string,{name:string;handle:string;avatar:string;items:Issue[]}>>((all,item)=>{const person=all[item.handle]||{name:item.author,handle:item.handle,avatar:item.avatar,items:[]};person.items.push(item);all[item.handle]=person;return all},{})),[items])
 const visible=category==='All issues'?items:items.filter(item=>item.category===category)
 return <main className="ccx-shell"><aside className="ccx-sidebar"><div className="ccx-brand"><img src="/nagorik-voice-logo.png" alt="Nagorik Voice"/><div><span>NAGORIK VOICE</span><b>City Corporation</b><small>Officer workspace</small></div></div><p>WORKSPACE</p><Nav icon={LayoutDashboard} label="Dashboard" active={view==='dashboard'} click={()=>setView('dashboard')}/><Nav icon={FileText} label="Daily posts" count={items.length} active={view==='posts'} click={()=>setView('posts')}/><Nav icon={Users} label="User details" count={users.length} active={view==='users'} click={()=>setView('users')}/><Nav icon={Tags} label="Categories" active={view==='categories'} click={()=>setView('categories')}/><div className="ccx-bottom"><button className="ccx-settings" onClick={()=>window.location.assign('/cc/settings')}><Settings size={18}/> Portal settings</button><button className="ccx-logout" onClick={logout}><LogOut size={18}/> Log out</button></div></aside><section className="ccx-content"><header className="ccx-header"><div><span className="eyebrow">CITY CORPORATION CONTROL</span><h1>{view==='dashboard'?'Daily operations dashboard':view==='posts'?'Daily citizen posts':view==='users'?'Citizen user details':'Category management'}</h1><p>{view==='dashboard'?'Review incoming civic issues, users and case escalation in one place.':'Live data from Nagorik Voice.'}</p></div><div className="ccx-officer"><span className="avatar">CC</span><span><b>CC Officer</b><small>Dhaka City Corporation</small></span></div></header>{view==='dashboard'&&<Dashboard items={items} open={setModal} setView={setView}/>} {view==='posts'&&<Posts items={visible} open={setModal} category={category} setCategory={setCategory}/>} {view==='users'&&<UsersPage users={users} open={setModal} ban={ban}/>} {view==='categories'&&<Categories items={items} category={category} setCategory={setCategory} open={setModal}/>}</section>{modal&&<FullPost issue={modal} close={()=>setModal(null)} forward={forward} remove={remove} ban={ban} updateStatus={updateStatus}/>}</main>
}
function Nav({icon:Icon,label,active,click,count}:{icon:any;label:string;active:boolean;click:()=>void;count?:number}){return <button className={`ccx-nav ${active?'active':''}`} onClick={click}><Icon size={19}/><span>{label}</span>{count!==undefined&&<i>{count}</i>}</button>}
function Dashboard({items,open,setView}:{items:Issue[];open:(item:Issue)=>void;setView:(view:View)=>void}){return <><div className="ccx-stats"><Metric value={items.length} label="Daily posts"/><Metric value={items.filter(i=>!i.sentToGovernment).length} label="Needs review"/><Metric value={items.filter(i=>i.sentToGovernment).length} label="Sent to Government"/><Metric value={items.filter(i=>i.governmentApproval).length} label="Approved work"/></div><section className="ccx-card"><div className="ccx-card-head"><div><h2>Recent daily posts</h2><p>Click a post to open its full report.</p></div><button onClick={()=>setView('posts')}>View all <ChevronRight size={17}/></button></div><Rows items={items.slice(0,6)} open={open}/></section></>}
function Metric({value,label}:{value:number;label:string}){return <div className="ccx-metric"><b>{value}</b><span>{label}</span></div>}
function Rows({items,open}:{items:Issue[];open:(item:Issue)=>void}){return <div className="ccx-post-rows">{items.length?items.map(item=><button className="ccx-post-row" key={item.id} onClick={()=>open(item)}>{item.image?<img src={item.image} alt=""/>:<span className="avatar">{item.avatar}</span>}<span><b>{item.title}</b><small>{item.author} · {item.location}</small></span><em className={status(item)}>{item.status}</em><ChevronRight size={18}/></button>):<div className="empty"><FileText/><h3>No posts found.</h3><p>New citizen reports will appear here.</p></div>}</div>}
function Posts({items,open,category,setCategory}:{items:Issue[];open:(item:Issue)=>void;category:string;setCategory:(value:string)=>void}){return <section className="ccx-card"><div className="ccx-card-head"><div><h2>All daily posts</h2><p>Select any report for its full-screen details.</p></div><select value={category} onChange={e=>setCategory(e.target.value)}><option>All issues</option>{categories.slice(1).map(item=><option key={item}>{item}</option>)}</select></div><Rows items={items} open={open}/></section>}
function UsersPage({users,open,ban}:{users:{name:string;handle:string;avatar:string;items:Issue[]}[];open:(item:Issue)=>void;ban:(item:Issue)=>Promise<void>}){const [active,setActive]=useState(users[0]?.handle);const user=users.find(item=>item.handle===active)||users[0];if(!user)return <section className="ccx-card empty"><Users/><h3>No citizen users yet.</h3></section>;return <div className="ccx-user-layout"><section className="ccx-card"><div className="ccx-card-head"><div><h2>User directory</h2><p>Choose a citizen to inspect details.</p></div></div><div className="ccx-user-rows">{users.map(item=><button className={item.handle===user.handle?'active':''} key={item.handle} onClick={()=>setActive(item.handle)}><span className="avatar">{item.avatar}</span><span><b>{item.name}</b><small>@{item.handle} · {item.items.length} posts</small></span><ChevronRight size={17}/></button>)}</div></section><aside className="ccx-user-detail"><div className="ccx-user-identity"><span className="avatar">{user.avatar}</span><div><h2>{user.name}</h2><p>@{user.handle}</p></div></div><h3>Account details</h3><Info label="Reports submitted" value={`${user.items.length} posts`}/><Info label="Latest report" value={user.items[0].time}/><Info label="Location" value={user.items[0].location}/><div className="ccx-user-actions"><button className="primary" onClick={()=>open(user.items[0])}><FileText size={16}/> View post</button><button className="ccx-danger" onClick={()=>ban(user.items[0])}><Ban size={16}/> Ban user</button></div></aside></div>}
function Info({label,value}:{label:string;value:string}){return <div className="ccx-info"><span>{label}</span><b>{value}</b></div>}
function Categories({items,category,setCategory,open}:{items:Issue[];category:string;setCategory:(value:string)=>void;open:(item:Issue)=>void}){const filtered=category==='All issues'?items:items.filter(item=>item.category===category);return <><section className="ccx-category-grid">{categories.slice(1).map(item=><button className={category===item?'active':''} key={item} onClick={()=>setCategory(item)}><Tags/><b>{item}</b><span>{items.filter(issue=>issue.category===item).length} reports</span></button>)}</section><section className="ccx-card"><div className="ccx-card-head"><div><h2>{category==='All issues'?'Choose a category':category}</h2><p>{filtered.length} reports</p></div><button onClick={()=>setCategory('All issues')}>Clear filter</button></div><Rows items={filtered} open={open}/></section></>}
function FullPost({issue,close,forward,remove,ban,updateStatus}:{issue:Issue;close:()=>void;forward:(issue:Issue)=>Promise<void>;remove:(issue:Issue)=>Promise<void>;ban:(issue:Issue)=>Promise<void>;updateStatus:(issue:Issue,status:Issue['status'])=>Promise<void>}){return <div className="ccx-modal"><article><header><div><span className="eyebrow">CITIZEN REPORT</span><h1>Post details</h1></div><button onClick={close} aria-label="Close"><X/></button></header><div className="ccx-modal-body">{issue.image&&<img src={issue.image} alt={issue.title}/>}<section><div className="ccx-modal-tags"><span className="category">{issue.category}</span><em className={status(issue)}>{issue.status}</em><span>{issue.severity} severity</span></div><h2>{issue.title}</h2><p>{issue.description}</p><div className="ccx-modal-user"><span className="avatar">{issue.avatar}</span><div><b>{issue.author}</b><small>@{issue.handle} · Citizen report</small></div></div><div className="ccx-location"><MapPin size={17}/><span>{issue.location}</span></div><label className="ccx-status-control"><span>CC case status</span><select value={issue.status} onChange={e=>updateStatus(issue,e.target.value as Issue['status'])}>{['Reported','Acknowledged','Under Review','In Progress','Resolved'].map(value=><option key={value}>{value}</option>)}</select></label><div className="ccx-modal-actions">{issue.sentToGovernment?<span className="sent-label"><CheckCircle2 size={17}/> Sent to Government</span>:<button className="primary" onClick={()=>forward(issue)}><Send size={17}/> Send to Government</button>}<button className="outline danger" onClick={()=>remove(issue)}><Trash2 size={17}/> Delete post</button><button className="ccx-danger" onClick={()=>ban(issue)}><Ban size={17}/> Ban user</button></div></section></div></article></div>}
