export type Status = 'Reported' | 'Acknowledged' | 'Under Review' | 'In Progress' | 'Resolved'
export type Issue = { id:number; title:string; description:string; author:string; handle:string; avatar:string; verified?:boolean; time:string; location:string; district:string; category:string; status:Status; severity:'Low'|'Medium'|'High'|'Critical'; supports:number; comments:number; shares:number; image:string; saved?:boolean; supported?:boolean; lat:number; lng:number }

export const categories = ['All issues','Broken Road','Pothole','Waterlogging','Drainage','Garbage/Waste','Traffic Congestion','Streetlight','Water Supply','Public Safety','Environmental Issue']
export const issues: Issue[] = [
 {id:1,title:'Large potholes making Road 12 unsafe',description:'This stretch has been damaged for several months. During rain, water collects inside the potholes and vehicles have to swerve suddenly. School children and rickshaw passengers are especially at risk.',author:'Sabbir Rahman',handle:'sabbir.r',avatar:'SR',time:'2 hours ago',location:'Uttara → Sector 4 → Road 12, Dhaka',district:'Dhaka',category:'Broken Road',status:'In Progress',severity:'High',supports:284,comments:38,shares:21,image:'https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&w=1200&q=85',lat:23.8728,lng:90.3959},
 {id:2,title:'Waste piling up beside the residential lane',description:'Garbage has not been collected for over a week. The smell is spreading to nearby homes and the footpath is almost completely blocked.',author:'Nusrat Jahan',handle:'nusrat.j',avatar:'NJ',time:'4 hours ago',location:'Mohammadpur → Block C, Dhaka',district:'Dhaka',category:'Garbage/Waste',status:'Acknowledged',severity:'Medium',supports:176,comments:29,shares:12,image:'https://images.unsplash.com/photo-1530587191325-3db32d826c18?auto=format&fit=crop&w=1200&q=85',lat:23.7658,lng:90.3584},
 {id:3,title:'Waterlogging outside Mirpur 10 market',description:'Even a short rainfall leaves knee-deep water here. Shopkeepers and commuters cannot move safely and the blocked drains need urgent clearing.',author:'Farhan Ahmed',handle:'farhan.a',avatar:'FA',time:'Yesterday',location:'Mirpur 10 → Roundabout, Dhaka',district:'Dhaka',category:'Waterlogging',status:'Under Review',severity:'Critical',supports:521,comments:84,shares:67,image:'https://images.unsplash.com/photo-1547683905-f686c993aae5?auto=format&fit=crop&w=1200&q=85',lat:23.8069,lng:90.3687},
 {id:4,title:'Streetlights not working near university gate',description:'Five consecutive streetlights are out. The road becomes very dark after 7 PM and students do not feel safe walking here.',author:'Ayesha Karim',handle:'ayesha.k',avatar:'AK',verified:true,time:'2 days ago',location:'GEC Circle, Chattogram',district:'Chattogram',category:'Streetlight',status:'Resolved',severity:'High',supports:198,comments:31,shares:14,image:'https://images.unsplash.com/photo-1519501025264-65ba15a82390?auto=format&fit=crop&w=1200&q=85',lat:22.3596,lng:91.8211},
 {id:5,title:'Damaged footpath forces people onto busy road',description:'Several concrete slabs are missing along this busy stretch. Pedestrians, including elderly residents, are being forced into traffic.',author:'Rafiul Islam',handle:'rafiul.i',avatar:'RI',time:'3 days ago',location:'Banani → Road 11, Dhaka',district:'Dhaka',category:'Public Safety',status:'Reported',severity:'High',supports:142,comments:19,shares:8,image:'https://images.unsplash.com/photo-1534274988757-a28bf1a57c17?auto=format&fit=crop&w=1200&q=85',lat:23.7937,lng:90.4066}
]

export const notifications = [
 {icon:'support',text:'Nusrat supported your report',detail:'Large potholes making Road 12 unsafe',time:'12 min'},
 {icon:'comment',text:'Farhan commented on your report',detail:'“I saw this today too. It is getting worse.”',time:'36 min'},
 {icon:'status',text:'Your issue status changed to In Progress',detail:'Uttara Road 12 · Updated by DNCC Zone 1',time:'2 hr'},
 {icon:'resolved',text:'An issue you followed was resolved',detail:'Streetlights near university gate',time:'1 day'}
]
