import { useMemo, useState } from 'react'
import { CheckCircle2, FileText, LayoutDashboard, LogOut, MapPin, Tags, Users, X } from 'lucide-react'
import { categories, type Issue } from './data'

type View='dashboard'|'cases'|'users'|'categories'
type Props={items:Issue[];approve:(issue:Issue,description:string,startDate:string)=>Promise<void>;remove:(issue:Issue)=>Promise<void>;logout:()=>Promise<void>}
const status=(item:Issue)=>`status ${item.status.toLowerCase().replaceAll(' ','-')}`

export default function GovernmentExperience({items,approve,remove,logout}:Props){
 const [view,setView]=useState<View>('dashboard'),[category,setCategory]=useState('All issues'),[active,setActive]=useState<Issue|null>(null)
 const users=useMemo(()=>Object.values(items.reduce<Record<string,{name:string;handle:string;avatar:string;items:Issue[]}>>((all,item)=>{const user=all[item.handle]||{name:item.author,handle:item.handle,avatar:item.avatar,items:[]};user.items.push(item);all[item.handle]=user;return all},{})),[items])
 const list=category==='All issues'?items:items.filter(item=>item.category===category)
 return <main className="ccx-shell govx"><aside className="ccx-sidebar"><div className="ccx-brand"><img src="/nagorik-voice-logo.png" alt="Nagorik Voice"/><div><span>NAGORIK VOICE</span><b>Government Portal</b><small>National service workspace</small></div></div><p>GOVERNMENT WORKSPACE</p><Nav icon={LayoutDashboard} text="Dashboard" active={view==='dashboard'} click={()=>setView('dashboard')}/><Nav icon={FileText} text="CC sent cases" count={items.length} active={view==='cases'} click={()=>setView('cases')}/><Nav icon={Users} text="Citizen details" count={users.length} active={view==='users'} click={()=>setView('users')}/><Nav icon={Tags} text="Categories" active={view==='categories'} click={()=>setView('categories')}/><div className="ccx-bottom"><button className="ccx-logout" onClick={logout}><LogOut size={18}/> Log out</button></div></aside><section className="ccx-content"><header className="ccx-header"><div><span className="eyebrow">NAGORIK VOICE / GOVERNMENT</span><h1>{view==='dashboard'?'Government operations dashboard':view==='cases'?'City Corporation sent cases':view==='users'?'Citizen details':'Case categories'}</h1><p>Review escalated citizen issues and publish Government work commitments.</p></div><div className="ccx-officer"><span className="avatar">GV</span><span><b>Government Officer</b><small>National service desk</small></span></div></header>{view==='dashboard'&&<><div className="ccx-stats"><Metric value={items.length} label="CC sent cases"/><Metric value={items.filter(i=>!i.governmentApproval).length} label="Awaiting approval"/><Metric value={items.filter(i=>i.governmentApproval).length} label="Work approved"/><Metric value={items.filter(i=>i.severity==='High'||i.severity==='Critical').length} label="High priority"/></div><section className="ccx-card"><Head title="Priority Government cases" copy="Cases forwarded by City Corporation."/><Rows items={items} open={setActive}/></section></>}{view==='cases'&&<section className="ccx-card"><div className="ccx-card-head"><div><h2>CC escalated cases</h2><p>Every original post and citizen detail is included.</p></div><select value={category} onChange={e=>setCategory(e.target.value)}><option>All issues</option>{categories.slice(1).map(c=><option key={c}>{c}</option>)}</select></div><Rows items={list} open={setActive}/></section>}{view==='users'&&<UsersPage users={users} open={setActive}/>} {view==='categories'&&<><section className="ccx-category-grid">{categories.slice(1).map(c=><button key={c} className={category===c?'active':''} onClick={()=>setCategory(c)}><Tags/><b>{c}</b><span>{items.filter(i=>i.category===c).length} cases</span></button>)}</section><section className="ccx-card"><Head title={category==='All issues'?'All categories':category} copy={`${list.length} escalated cases`}/><Rows items={list} open={setActive}/></section></>}</section>{active&&<CasePage item={active} close={()=>setActive(null)} approve={approve} remove={remove}/>}</main>
}
function Nav({icon:Icon,text,count,active,click}:{icon:any;text:string;count?:number;active:boolean;click:()=>void}){return <button className={`ccx-nav ${active?'active':''}`} onClick={click}><Icon size={19}/><span>{text}</span>{count!==undefined&&<i>{count}</i>}</button>}
function Metric({value,label}:{value:number;label:string}){return <div className="ccx-metric govx-metric"><b>{value}</b><span>{label}</span></div>}
function Head({title,copy}:{title:string;copy:string}){return <div className="ccx-card-head"><div><h2>{title}</h2><p>{copy}</p></div></div>}
function Rows({items,open}:{items:Issue[];open:(item:Issue)=>void}){return <div className="ccx-post-rows">{items.length?items.map(item=><button className="ccx-post-row" onClick={()=>open(item)} key={item.id}>{item.image?<img src={item.image} alt=""/>:<span className="avatar">{item.avatar}</span>}<span><b>{item.title}</b><small>{item.author} · {item.location}</small></span><em className={status(item)}>{item.governmentApproval?'Approved':item.status}</em><span>›</span></button>):<div className="empty"><FileText/><h3>No cases yet.</h3><p>Cases sent by City Corporation will appear here.</p></div>}</div>}
function UsersPage({users,open}:{users:{name:string;handle:string;avatar:string;items:Issue[]}[];open:(item:Issue)=>void}){const [selected,setSelected]=useState(users[0]?.handle);const user=users.find(u=>u.handle===selected)||users[0];if(!user)return <div className="ccx-card empty"><Users/><h3>No citizen details yet.</h3></div>;return <div className="ccx-user-layout"><section className="ccx-card"><Head title="Citizen directory" copy="Details forwarded with each CC case."/>{users.map((u,index)=><button className={`ccx-user-row ${u.handle===user.handle?'active':''}`} onClick={()=>setSelected(u.handle)} key={u.handle}><b>{index+1}.</b><span className="avatar">{u.avatar}</span><span><b>{u.name}</b><small>@{u.handle} · {u.items.length} cases</small></span><span>›</span></button>)}</section><aside className="ccx-user-detail govx-citizen-detail"><div className="ccx-user-identity"><span className="avatar">{user.avatar}</span><div><h2>{user.name}</h2><p>@{user.handle}</p></div></div><h3>Account details</h3><Info label="CC sent cases" value={`${user.items.length} cases`}/><Info label="Latest address" value={user.items[0].location}/><div className="govx-citizen-actions"><button className="primary" onClick={()=>open(user.items[0])}><FileText size={16}/> View full case</button></div><h3>Recent cases</h3>{user.items.slice(0,3).map(item=><button className="govx-mini-case" key={item.id} onClick={()=>open(item)}><span>{item.title}</span><span>›</span></button>)}</aside></div>}
function Info({label,value}:{label:string;value:string}){return <div className="ccx-info"><span>{label}</span><b>{value}</b></div>}
function CasePage({item,close,approve,remove}:{item:Issue;close:()=>void;approve:(item:Issue,description:string,date:string)=>Promise<void>;remove:(item:Issue)=>Promise<void>}){const [description,setDescription]=useState(item.governmentApproval?.description||''),[date,setDate]=useState(item.governmentApproval?.startDate||'');const removeCase=async()=>{if(confirm(`Remove “${item.title}” from the Government portal? The public post will remain on Nagorik Voice.`)){await remove(item);close()}};return <div className="ccx-modal govx-modal"><article><header><button onClick={close}><X/></button><div><span className="eyebrow">GOVERNMENT CASE REVIEW</span><h1>Full case details</h1></div></header><div className="ccx-modal-body">{item.image&&<img src={item.image} alt=""/>}<section><div className="ccx-modal-tags"><span className="category">{item.category}</span><em className={status(item)}>{item.status}</em><span>{item.severity} priority</span></div><h2>{item.title}</h2><p>{item.description}</p><div className="ccx-modal-user"><span className="avatar">{item.avatar}</span><div><b>{item.author}</b><small>@{item.handle} · Citizen report sent by City Corporation</small></div></div><div className="ccx-location"><MapPin size={17}/><span>{item.location}</span></div><form className="govx-approval" onSubmit={async e=>{e.preventDefault();if(description&&date){await approve(item,description,date);close()}}}><h3>{item.governmentApproval?'Update work commitment':'Approve & publish work commitment'}</h3><label>Public work update<textarea value={description} onChange={e=>setDescription(e.target.value)} required placeholder="We have reviewed this issue. Work will begin shortly."/></label><label>Expected work start date<input type="date" value={date} onChange={e=>setDate(e.target.value)} required/></label><button className="primary"><CheckCircle2 size={17}/> Approve & publish</button><button type="button" className="govx-remove-case" onClick={removeCase}>Remove from Government</button></form></section></div></article></div>}
