import { useEffect, useState } from 'react'
import { ArrowLeft, KeyRound, Mail, Save, ShieldCheck } from 'lucide-react'
import { getOfficerRole } from './lib/database'
import { supabase } from './lib/supabase'
import './cc-settings-page.css'

export default function GovernmentSettingsPage(){
 const [email,setEmail]=useState(''),[currentPassword,setCurrentPassword]=useState(''),[newPassword,setNewPassword]=useState(''),[confirm,setConfirm]=useState(''),[notice,setNotice]=useState('')
 useEffect(()=>{getOfficerRole().then(async role=>{if(role!=='government_officer'){window.location.assign('/govt');return}const {data:{user}}=await supabase.auth.getUser();setEmail(user?.email||'')})},[])
 const save=async(event:React.FormEvent)=>{event.preventDefault();setNotice('');if(newPassword&&newPassword!==confirm){setNotice('New passwords do not match.');return}if(newPassword&&newPassword.length<6){setNotice('New password must be at least 6 characters.');return}const {error:verifyError}=await supabase.auth.signInWithPassword({email,password:currentPassword});if(verifyError){setNotice('Current password is incorrect.');return}const payload:{email?:string;password?:string}={};if(email)payload.email=email;if(newPassword)payload.password=newPassword;const {error}=await supabase.auth.updateUser(payload);setNotice(error?error.message:'Credentials updated securely. Check your email if you changed it.')}
 return <main className="cc-settings-page govt-settings-page"><header><button onClick={()=>window.location.assign('/govt')}><ArrowLeft size={18}/> Back to Government portal</button><span>Government · Secure settings</span></header><section><div className="cc-settings-page-head"><span className="eyebrow">NAGORIK VOICE / GOVERNMENT</span><h1>Government portal settings</h1><p>Manage the real Supabase email and password for this officer account.</p></div><div className="cc-settings-page-grid"><form className="cc-settings-form" onSubmit={save}><div className="cc-settings-page-icon"><ShieldCheck/></div><h2>Change portal credentials</h2><label><span><Mail size={16}/> Officer email</span><input value={email} onChange={e=>setEmail(e.target.value)} type="email"/></label><label><span><KeyRound size={16}/> Current password</span><input value={currentPassword} onChange={e=>setCurrentPassword(e.target.value)} type="password" required/></label><label><span><KeyRound size={16}/> New password</span><input value={newPassword} onChange={e=>setNewPassword(e.target.value)} type="password" placeholder="Leave blank to keep current password"/></label><label><span><KeyRound size={16}/> Confirm new password</span><input value={confirm} onChange={e=>setConfirm(e.target.value)} type="password"/></label>{notice&&<p className="cc-settings-page-error">{notice}</p>}<button className="primary"><Save size={17}/> Save securely</button></form><aside className="cc-settings-info"><span className="avatar">GV</span><h2>Production security</h2><p>Credentials are stored by Supabase Auth, not in this browser.</p><div><b>Email changes</b><span>Supabase sends a confirmation email.</span></div><div><b>Password changes</b><span>Your current password is required.</span></div></aside></div></section></main>
}
