import { useEffect } from 'react'

// Keeps the original source text for every DOM node, so translation survives React re-renders.
const bn:Record<string,string>={
 'Search areas, issues or people':'এলাকা, সমস্যা বা মানুষ খুঁজুন','Report issue':'সমস্যা জানান','Home':'হোম','Explore':'এক্সপ্লোর','Browse areas':'এলাকা দেখুন','Issue map':'সমস্যার মানচিত্র','Saved posts':'সংরক্ষিত পোস্ট','Notifications':'নোটিফিকেশন','View your profile':'প্রোফাইল দেখুন','Create report':'রিপোর্ট তৈরি করুন','Edit profile':'প্রোফাইল সম্পাদনা','Find nearby issues':'কাছের সমস্যা খুঁজুন','Your community activity':'আপনার কমিউনিটি কার্যক্রম','This month':'এই মাসে','Reports shared':'শেয়ার করা রিপোর্ট','Community supports':'কমিউনিটি সমর্থন','Issues resolved':'সমাধান হওয়া সমস্যা','Make your area better':'আপনার এলাকা আরও সুন্দর করুন','Report civic issues and support your neighbours.':'নাগরিক সমস্যা জানান এবং প্রতিবেশীদের সমর্থন করুন।',
 'YOUR COMMUNITY FEED':'আপনার কমিউনিটি ফিড','Good morning, Arafat':'সুপ্রভাত, আরাফাত','See what your community is talking about today.':'আজ আপনার কমিউনিটি কী নিয়ে কথা বলছে দেখুন।','Dhaka':'ঢাকা','Partly cloudy':'আংশিক মেঘলা','Report a problem in your area...':'আপনার এলাকার একটি সমস্যা জানান...','Photo':'ছবি','Location':'লোকেশন','All issues':'সব সমস্যা','Community reports':'কমিউনিটি রিপোর্ট','issues in your feed':'টি সমস্যা আপনার ফিডে','Newest first':'সর্বশেষ আগে','Most supported':'সবচেয়ে সমর্থিত','Support':'সমর্থন','Supported':'সমর্থন করেছেন','Comment':'মন্তব্য','Share':'শেয়ার','Save':'সংরক্ষণ','Saved issues':'সংরক্ষিত সমস্যা','Reports you bookmarked to revisit later':'পরে দেখার জন্য সংরক্ষিত আপনার রিপোর্ট',
 'Trending in Bangladesh':'বাংলাদেশে ট্রেন্ডিং','See all':'সব দেখুন','supports':'সমর্থন','24 issues resolved':'২৪টি সমস্যা সমাধান হয়েছে','by community action this month':'এই মাসে কমিউনিটির উদ্যোগে',
 'DISCOVER':'আবিষ্কার করুন','Explore civic issues':'নাগরিক সমস্যা খুঁজুন','See what communities across Bangladesh are reporting and supporting.':'বাংলাদেশজুড়ে কমিউনিটির রিপোর্ট ও সমর্থন দেখুন।','Active reports':'সক্রিয় রিপোর্ট','Resolved this year':'এ বছর সমাধান','Active areas':'সক্রিয় এলাকা','Trending now':'এখন ট্রেন্ডিং','Browse by category':'বিষয়ভিত্তিক দেখুন',
 'LOCATION DIRECTORY':'এলাকা তালিকা','What’s happening near you?':'আপনার আশেপাশে কী হচ্ছে?','Choose an area to discover, follow and support local civic reports.':'স্থানীয় রিপোর্ট খুঁজতে, অনুসরণ করতে ও সমর্থন করতে একটি এলাকা বেছে নিন।','Division':'বিভাগ','District':'জেলা','Area / Thana':'এলাকা / থানা','All areas':'সব এলাকা','View reports':'রিপোর্ট দেখুন','AREA OVERVIEW':'এলাকা পর্যালোচনা','Follow area':'এলাকা অনুসরণ করুন','Following area':'এলাকা অনুসরণ করছেন','Reported':'রিপোর্ট করা হয়েছে','In progress':'চলমান','Resolved':'সমাধান হয়েছে','Recently reported community issues':'সম্প্রতি জানানো কমিউনিটি সমস্যা',
 'LIVE ISSUE MAP':'লাইভ সমস্যা মানচিত্র','Reports across Bangladesh':'বাংলাদেশজুড়ে রিপোর্ট','Explore public problems by location, category and current status.':'লোকেশন, ধরন ও বর্তমান অবস্থা অনুযায়ী জনসমস্যা দেখুন।','All categories':'সব বিভাগ','All statuses':'সব অবস্থা','All severity':'সব গুরুত্ব','visible reports':'টি দৃশ্যমান রিপোর্ট','View issue →':'সমস্যাটি দেখুন →',
 'STAY UPDATED':'সর্বশেষ আপডেট','Updates from your reports, followed issues and community.':'আপনার রিপোর্ট, অনুসরণ করা সমস্যা ও কমিউনিটির আপডেট।','All':'সব','Mentions':'উল্লেখ','Updates':'আপডেট','Mark all as read':'সব পঠিত হিসেবে চিহ্নিত করুন','All caught up':'সব দেখা হয়েছে','No notifications in this category.':'এই বিভাগে কোনো নোটিফিকেশন নেই।',
 'My recent reports':'আমার সাম্প্রতিক রিপোর্ট','Your published civic issues':'আপনার প্রকাশিত নাগরিক সমস্যা','Reports':'রিপোর্ট','Saved':'সংরক্ষিত','Activity':'কার্যক্রম','About':'পরিচিতি','Edit cover':'কভার পরিবর্তন','You have not published a report yet.':'আপনি এখনও কোনো রিপোর্ট প্রকাশ করেননি।','No saved reports yet.':'কোনো সংরক্ষিত রিপোর্ট নেই।','Your activity':'আপনার কার্যক্রম','Profile details':'প্রোফাইলের তথ্য','Lives in':'বাসস্থান','Email':'ইমেইল','Phone':'ফোন','Birthday':'জন্মদিন','Work':'কাজ','Education':'শিক্ষা','Not added':'যোগ করা হয়নি।','No bio added yet.':'এখনও কোনো পরিচিতি যোগ করা হয়নি।','Full name':'পূর্ণ নাম','Username':'ইউজারনেম','Bio':'পরিচিতি','City':'শহর','Save profile':'প্রোফাইল সংরক্ষণ','YOUR PROFILE':'আপনার প্রোফাইল',
 'REPORT A CIVIC ISSUE':'নাগরিক সমস্যা জানান','Tell us what happened':'কী ঘটেছে বলুন','Photo & location':'ছবি ও লোকেশন','Review and publish':'পর্যালোচনা ও প্রকাশ','Issue':'সমস্যা','Keep it civic and factual':'নাগরিক ও তথ্যভিত্তিক রাখুন','Only publish genuine public or community issues.':'শুধু প্রকৃত জনসাধারণ বা কমিউনিটির সমস্যা প্রকাশ করুন।','Issue title':'সমস্যার শিরোনাম','Description':'বিবরণ','Category':'বিভাগ','Severity':'গুরুত্ব','Low':'কম','Medium':'মাঝারি','High':'বেশি','Critical':'জরুরি','Continue':'পরবর্তী','Back':'পেছনে','Photo evidence':'ছবির প্রমাণ','Add a photo':'ছবি তুলুন','Take or select a photo':'ছবি তুলুন','Choose an image from your device.':'ক্যামেরা ব্যবহার করে একটি ছবি তুলুন।','Tap to use your camera or photo library':'ক্যামেরা চালু করতে ট্যাপ করুন।','Location / address':'লোকেশন / ঠিকানা','Road / street':'সড়ক / রাস্তা','Use my location':'আমার লোকেশন ব্যবহার করুন','Publish issue':'রিপোর্ট প্রকাশ করুন',
 'Broken Road':'ভাঙা রাস্তা','Pothole':'রাস্তার গর্ত','Waterlogging':'জলাবদ্ধতা','Drainage':'ড্রেনেজ','Garbage/Waste':'আবর্জনা','Traffic Congestion':'যানজট','Streetlight':'স্ট্রিটলাইট','Water Supply':'পানি সরবরাহ','Public Safety':'জননিরাপত্তা','Environmental Issue':'পরিবেশগত সমস্যা',
 'Large potholes making Road 12 unsafe':'রোড ১২-এর বড় গর্ত চলাচলকে ঝুঁকিপূর্ণ করছে','Waste piling up beside the residential lane':'আবাসিক গলির পাশে জমে আছে আবর্জনা','Waterlogging outside Mirpur 10 market':'মিরপুর ১০ বাজারের সামনে জলাবদ্ধতা','Streetlights not working near university gate':'বিশ্ববিদ্যালয় গেটের পাশে স্ট্রিটলাইট নষ্ট','Damaged footpath forces people onto busy road':'ভাঙা ফুটপাথ মানুষকে ব্যস্ত সড়কে নামতে বাধ্য করছে',
 'This stretch has been damaged for several months. During rain, water collects inside the potholes and vehicles have to swerve suddenly. School children and rickshaw passengers are especially at risk.':'এই সড়কটি কয়েক মাস ধরে ক্ষতিগ্রস্ত। বৃষ্টিতে গর্তে পানি জমে এবং যানবাহনকে হঠাৎ দিক পরিবর্তন করতে হয়। স্কুলশিক্ষার্থী ও রিকশা যাত্রীরা বেশি ঝুঁকিতে আছেন।','Garbage has not been collected for over a week. The smell is spreading to nearby homes and the footpath is almost completely blocked.':'এক সপ্তাহের বেশি সময় ধরে আবর্জনা অপসারণ করা হয়নি। দুর্গন্ধ আশেপাশের বাড়িতে ছড়াচ্ছে এবং ফুটপাথ প্রায় বন্ধ।','Even a short rainfall leaves knee-deep water here. Shopkeepers and commuters cannot move safely and the blocked drains need urgent clearing.':'অল্প বৃষ্টিতেই এখানে হাঁটুপানি জমে। দোকানদার ও যাত্রীরা নিরাপদে চলাচল করতে পারেন না; বন্ধ ড্রেন দ্রুত পরিষ্কার প্রয়োজন।','Five consecutive streetlights are out. The road becomes very dark after 7 PM and students do not feel safe walking here.':'টানা পাঁচটি স্ট্রিটলাইট নষ্ট। সন্ধ্যার পর সড়কটি অন্ধকার হয়ে যায় এবং শিক্ষার্থীরা নিরাপদ বোধ করেন না।','Several concrete slabs are missing along this busy stretch. Pedestrians, including elderly residents, are being forced into traffic.':'ব্যস্ত সড়কটির ফুটপাথের কয়েকটি কংক্রিট স্ল্যাব নেই। বয়স্কসহ পথচারীরা যানবাহনের মধ্যে চলতে বাধ্য হচ্ছেন।',
 'Uttara → Sector 4 → Road 12, Dhaka':'উত্তরা → সেক্টর ৪ → রোড ১২, ঢাকা','Mohammadpur → Block C, Dhaka':'মোহাম্মদপুর → ব্লক সি, ঢাকা','Mirpur 10 → Roundabout, Dhaka':'মিরপুর ১০ → গোলচত্বর, ঢাকা','GEC Circle, Chattogram':'জিইসি সার্কেল, চট্টগ্রাম','Banani → Road 11, Dhaka':'বনানী → রোড ১১, ঢাকা'
}

export default function LanguageTranslator(){
 useEffect(()=>{
  let isBangla=localStorage.getItem('nv-language')==='bn'
  const originals=new WeakMap<Text,string>()
  const translateNode=(node:Text)=>{if(node.parentElement?.closest('.language'))return;const original=originals.get(node)??node.nodeValue??'';originals.set(node,original);const lead=original.match(/^\s*/)?.[0]||'',tail=original.match(/\s*$/)?.[0]||'',core=original.trim(),next=lead+(isBangla?(bn[core]||core):core)+tail;if(node.nodeValue!==next)node.nodeValue=next}
  const translateTree=(root:Node)=>{if(root.nodeType===Node.TEXT_NODE)translateNode(root as Text);const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);let node:Text|null;while(node=walker.nextNode() as Text|null)translateNode(node)}
  const setLanguage=()=>{document.documentElement.lang=isBangla?'bn':'en';translateTree(document.body);document.querySelectorAll<HTMLElement>('.language').forEach(button=>{const label=[...button.childNodes].find(node=>node.nodeType===Node.TEXT_NODE);if(label)label.nodeValue=` ${isBangla?'English':'বাংলা'}`})}
  const observer=new MutationObserver(records=>records.forEach(record=>{if(record.type==='characterData')translateNode(record.target as Text);record.addedNodes.forEach(translateTree)}))
  const toggle=(event:MouseEvent)=>{if(!(event.target as HTMLElement).closest('.language'))return;isBangla=!isBangla;localStorage.setItem('nv-language',isBangla?'bn':'en');queueMicrotask(setLanguage)}
  observer.observe(document.body,{childList:true,subtree:true,characterData:true});document.addEventListener('click',toggle);setLanguage()
  return()=>{observer.disconnect();document.removeEventListener('click',toggle)}
 },[])
 return null
}
