import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App'
import AdminPortal from './AdminPortal'
import CCSettingsPage from './CCSettingsPage'
import GovernmentSettingsPage from './GovernmentSettingsPage'
import GovernmentApprovedPage from './GovernmentApprovedPage'
import LanguageTranslator from './LanguageTranslator'
import './styles.css'
import './logo.css'
import './features.css'
import './auth.css'
import './login-logo.css'
import './profile-menu.css'
import './profile-settings.css'
import './cc-portal.css'
import './cc-experience.css'
import './cc-category-fix.css'
import './cc-layout-alignment.css'
import './govt-settings-shortcut.css'
import './government-experience.css'
import './government-send-toast.css'
import './govt-user-directory-fix.css'
import './govt-citizen-detail.css'
import './government-approved-page.css'
import './govt-citizen-rebuild.css'
import './govt-citizen-reference-layout.css'
import './govt-citizen-soft-ui.css'
import './govt-citizen-correct-selector.css'
import './approved-remove.css'
import './government-approved-rail.css'
import './cc-status-control.css'
import './portal-post-tags.css'
import './portal-watermark.css'
import './govt-remove-case.css'
const path = window.location.pathname.toLowerCase()
const isCCSettings = path === '/cc/settings'
const isGovernmentSettings = path === '/govt/settings'
const isGovernmentApproved = path === '/govt/approved'
const portal = path === '/cc' ? 'cc' : path === '/govt' || path === '/admin' ? 'govt' : null
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode>{isCCSettings?<CCSettingsPage/>:isGovernmentSettings?<GovernmentSettingsPage/>:isGovernmentApproved?<GovernmentApprovedPage/>:portal?<AdminPortal portal={portal}/>:<><LanguageTranslator/><App/></>}</React.StrictMode>)
