import { useRef, useState } from 'react'
import { Image as ImageIcon, MapPin, Navigation, Send, ShieldCheck, X } from 'lucide-react'
import { categories, type Issue } from './data'

const mobileDevice=()=>typeof navigator!=='undefined'&&(/Android|iPhone|iPad|iPod/i.test(navigator.userAgent)||navigator.maxTouchPoints>1)

export default function MobileReportModal({close,publish}:{close:()=>void;publish:(issue:Issue)=>void}){
 const [step,setStep]=useState(1),[title,setTitle]=useState(''),[description,setDescription]=useState(''),[category,setCategory]=useState('Broken Road'),[severity,setSeverity]=useState<Issue['severity']>('Medium'),[area,setArea]=useState(''),[road,setRoad]=useState(''),[preview,setPreview]=useState(''),[coords,setCoords]=useState<[number,number] | null>(null),[locationStatus,setLocationStatus]=useState('Choose a place or use your current location.'),[agreed,setAgreed]=useState(false)
 const fileRef=useRef<HTMLInputElement>(null), mobile=mobileDevice(), issueValid=Boolean(title.trim()&&description.trim()), valid=Boolean(issueValid&&area.trim())
 const takePhoto=()=>{if(mobile)fileRef.current?.click()}
 const useLocation=()=>{if(!navigator.geolocation){setLocationStatus('Location is not supported by this browser.');return}setLocationStatus('Finding your location…');navigator.geolocation.getCurrentPosition(p=>{const next:[number,number]=[p.coords.latitude,p.coords.longitude];setCoords(next);setArea(`Current location (${next[0].toFixed(4)}, ${next[1].toFixed(4)})`);setLocationStatus('Current location added to your report.')},()=>setLocationStatus('Location access was not allowed. Enter your area manually.'),{enableHighAccuracy:true,timeout:10000})}
 const submit=()=>{if(!valid||!agreed)return;publish({id:Date.now(),title,description,author:'Arafat Rahman',handle:'arafat.r',avatar:'AR',time:'Just now',location:`${area}${road?` → ${road}`:''}`,district:'Dhaka',category,status:'Reported',severity,supports:0,comments:0,shares:0,image:preview||'https://images.unsplash.com/photo-1480714378408-67cf0d13bc1b?auto=format&fit=crop&w=1200&q=85',lat:coords?.[0]||23.81,lng:coords?.[1]||90.39})}
 return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className="modal"><div className="modal-head"><div><span>REPORT A CIVIC ISSUE</span><h2>{step===1?'Tell us what happened':step===2?'Photo & location':'Review and publish'}</h2></div><button onClick={close}><X/></button></div><div className="steps"><div className="active"><i>1</i><span>Issue</span></div><hr className={step>=2?'active':''}/><div className={step>=2?'active':''}><i>2</i><span>Location</span></div><hr className={step>=3?'active':''}/><div className={step>=3?'active':''}><i>3</i><span>Review</span></div></div><div className="modal-body">
 {step===1&&<><div className="rule-note"><ShieldCheck/><div><b>Keep it civic and factual</b><p>Only publish genuine public or community issues.</p></div></div><label className="field"><b>Issue title</b><input value={title} maxLength={100} onChange={e=>setTitle(e.target.value)} placeholder="e.g. Large pothole causing traffic problems"/></label><label className="field"><b>Description</b><textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="Describe the issue…"/></label><div className="form-grid"><label className="field"><b>Category</b><select value={category} onChange={e=>setCategory(e.target.value)}>{categories.slice(1).map(c=><option key={c}>{c}</option>)}</select></label><label className="field"><b>Severity</b><select value={severity} onChange={e=>setSeverity(e.target.value as Issue['severity'])}><option>Low</option><option>Medium</option><option>High</option><option>Critical</option></select></label></div></>}
 {step===2&&<><label className="field"><b>Live photo evidence</b><div className={`upload ${mobile?'':'desktop-disabled'}`} onClick={takePhoto}>{preview?<img src={preview} alt="Captured evidence"/>:<><div><ImageIcon/></div><b>{mobile?'Take a live photo':'Available on mobile only'}</b><p>{mobile?'Tap to open your phone camera':'Open this page from a phone to take an instant camera photo.'}</p></>}<input ref={fileRef} hidden type="file" accept="image/*" capture="environment" onChange={e=>{const file=e.target.files?.[0];if(file)setPreview(URL.createObjectURL(file))}}/></div></label><label className="field"><b>Location / address</b><input value={area} onChange={e=>setArea(e.target.value)} placeholder="Search or enter any area"/></label><label className="field"><b>Road / street</b><input value={road} onChange={e=>setRoad(e.target.value)} placeholder="e.g. Road 12"/></label><div className="google-map">{coords?<iframe title="Selected Google Map location" src={`https://www.google.com/maps?q=${coords[0]},${coords[1]}&z=16&output=embed`}/>:<div><MapPin size={26}/><span>Google Map preview will appear after you use your location.</span></div>}</div><div className="pin-box"><div><MapPin/><span>{locationStatus}</span></div><button onClick={useLocation}><Navigation size={16}/> Use my location</button></div></>}
 {step===3&&<><div className="review-card">{preview&&<img src={preview} alt="Evidence"/>}<span className="category">{category}</span><h3>{title||'Untitled issue'}</h3><p>{description}</p><div className="location-line"><MapPin size={15}/>{area}{road?` → ${road}`:''}</div></div><label className="check-row"><input type="checkbox" checked={agreed} onChange={e=>setAgreed(e.target.checked)}/><span>I confirm this is a genuine public/community issue and the information is accurate.</span></label></>}
 </div><div className="modal-foot">{step>1?<button className="outline" onClick={()=>setStep(step-1)}>Back</button>:<span/>}{step<3?<button className="primary" disabled={step===1&&!issueValid} onClick={()=>setStep(step+1)}>Continue</button>:<button className="primary" disabled={!valid||!agreed} onClick={submit}><Send size={17}/> Publish issue</button>}</div></div></div>
}
