import { useState } from 'react'
import { MapPin, Pencil, Save, X } from 'lucide-react'
import type { Issue } from './data'
import { initials, type AppUser } from './Auth'
import { updateProfile } from './lib/database'

export default function ProfileExperience({issues,openIssue,user,updateUser,openSettings}:{issues:Issue[];openIssue:(issue:Issue)=>void;user:AppUser;updateUser:(user:AppUser)=>void;openSettings:()=>void}){
 const [editing,setEditing]=useState(false),[draft,setDraft]=useState(user),[tab,setTab]=useState('Reports')
 const reports=issues.filter(issue=>issue.handle===user.username).slice(0,6),saved=issues.filter(issue=>issue.saved)
 const save=async()=>{const next={...draft,avatar:initials(draft.name)};await updateProfile(next);updateUser(next);setEditing(false)}
 const cards=(list:Issue[],empty:string)=><div className="listing"><div className="compact-grid">{list.length?list.map(issue=><button className="compact-card" key={issue.id} onClick={()=>openIssue(issue)}>{issue.image&&<img src={issue.image} alt=""/>}<span><h3>{issue.title}</h3><p><MapPin size={14}/>{issue.location}</p><small>{issue.supports} supports</small></span></button>):<p className="profile-empty">{empty}</p>}</div></div>
 return <div className="page profile-page"><div className={`cover ${user.coverUrl?'profile-cover-image':''}`} style={user.coverUrl?{backgroundImage:`linear-gradient(90deg,rgba(8,45,97,.18),rgba(8,45,97,.08)),url(${user.coverUrl})`}:undefined}><div className="cover-pattern"/></div><div className="profile-header"><div className="avatar profile-avatar">{user.avatarUrl?<img src={user.avatarUrl} alt={`${user.name} profile`}/>:user.avatar}</div><div className="profile-copy"><h1>{user.name}</h1><p>@{user.username} · {user.city}</p><span>Community member reporting issues that matter in their neighbourhood.</span></div><button className="outline" onClick={()=>window.matchMedia('(max-width: 800px)').matches?openSettings():(setDraft(user),setEditing(true))}><Pencil size={15}/> Edit profile</button></div><div className="profile-stats"><div className="stat"><b>{reports.length}</b><span>Reports</span></div><div className="stat"><b>{saved.length}</b><span>Saved</span></div><div className="stat"><b>8</b><span>Areas followed</span></div></div><div className="profile-tabs">{['Reports','Saved','About'].map(item=><button key={item} className={tab===item?'active':''} onClick={()=>setTab(item)}>{item}</button>)}</div>{tab==='Reports'&&cards(reports,'You have not published a report yet.')}{tab==='Saved'&&cards(saved,'No saved reports yet.')}{tab==='About'&&<section className="about-card"><h2>Profile details</h2><div><b>Email</b><span>{user.email}</span></div><div><b>Lives in</b><span>{user.city}</span></div><div><b>Phone</b><span>{user.phone||'Not added yet'}</span></div><div><b>Address</b><span>{user.address||'Not added yet'}</span></div></section>}{editing&&<div className="modal-backdrop"><section className="modal profile-editor"><div className="modal-head"><div><span>YOUR PROFILE</span><h2>Edit profile</h2></div><button onClick={()=>setEditing(false)}><X/></button></div><div className="modal-body"><label className="field"><b>Full name</b><input value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label className="field"><b>City</b><input value={draft.city} onChange={e=>setDraft({...draft,city:e.target.value})}/></label></div><div className="modal-foot"><span/><button className="primary" onClick={save}><Save size={16}/> Save profile</button></div></section></div>}</div>
}
