import { useRef, useState } from 'react'
import { Camera, MapPin, Pencil, Save, X } from 'lucide-react'
import type { Issue } from './data'

type ProfileData = { name:string; username:string; bio:string; city:string; phone:string; email:string; birthday:string; work:string; education:string; avatar:string; cover:string }
const initial:ProfileData = {name:'Arafat Rahman',username:'arafat.r',bio:'Community member reporting issues that matter to our neighbourhoods.',city:'Dhaka, Bangladesh',phone:'',email:'',birthday:'',work:'',education:'',avatar:'',cover:''}

export default function ProfileExperience({issues,openIssue}:{issues:Issue[];openIssue:(issue:Issue)=>void}) {
 const [profile,setProfile]=useState<ProfileData>(()=>{try{return {...initial,...JSON.parse(localStorage.getItem('nv-profile')||'{}')}}catch{return initial}})
 const [editing,setEditing]=useState(false),[tab,setTab]=useState('Reports')
 const avatarRef=useRef<HTMLInputElement>(null), coverRef=useRef<HTMLInputElement>(null)
 const setImage=(key:'avatar'|'cover',file?:File)=>{if(file)setProfile(p=>({...p,[key]:URL.createObjectURL(file)}))}
 const save=()=>{localStorage.setItem('nv-profile',JSON.stringify(profile));setEditing(false)}
 const reports=issues.filter(issue=>issue.author==='Arafat Rahman').slice(0,6)
 return <div className="page profile-page">
  <div className="cover" style={profile.cover?{backgroundImage:`url(${profile.cover})`,backgroundSize:'cover',backgroundPosition:'center'}:undefined}><div className="cover-pattern"/><button onClick={()=>coverRef.current?.click()}><Camera size={16}/> Edit cover</button><input hidden ref={coverRef} type="file" accept="image/*" onChange={e=>setImage('cover',e.target.files?.[0])}/></div>
  <div className="profile-header"><button className="profile-picture-button avatar profile-avatar" onClick={()=>avatarRef.current?.click()} style={profile.avatar?{backgroundImage:`url(${profile.avatar})`,backgroundSize:'cover',color:'transparent'}:undefined}>{profile.avatar?'':profile.name.split(' ').map(n=>n[0]).slice(0,2).join('')}<span><Camera size={17}/></span></button><input hidden ref={avatarRef} type="file" accept="image/*" onChange={e=>setImage('avatar',e.target.files?.[0])}/><div className="profile-copy"><h1>{profile.name}</h1><p>@{profile.username} · {profile.city}</p><span>{profile.bio}</span></div><button className="outline" onClick={()=>setEditing(true)}><Pencil size={15}/> Edit profile</button></div>
  <div className="profile-stats"><div className="stat"><b>{reports.length}</b><span>Reports</span></div><div className="stat"><b>1,284</b><span>Supports received</span></div><div className="stat"><b>4</b><span>Resolved reports</span></div><div className="stat"><b>8</b><span>Areas followed</span></div></div>
  <div className="profile-tabs">{['Reports','About'].map(item=><button key={item} className={tab===item?'active':''} onClick={()=>setTab(item)}>{item}</button>)}</div>
  {tab==='Reports'?<div className="listing"><div className="feed-title"><div><h2>My recent reports</h2><p>Your published civic issues</p></div></div>{reports.length?<div className="compact-grid">{reports.map(issue=><div className="compact-card" key={issue.id} onClick={()=>openIssue(issue)}><img src={issue.image}/><div><h3>{issue.title}</h3><p><MapPin size={14}/>{issue.location}</p></div></div>)}</div>:<p className="profile-empty">You have not published a report yet.</p>}</div>:<section className="about-card"><h2>About</h2><p>{profile.bio||'No bio added yet.'}</p><div><b>Lives in</b><span>{profile.city||'Not added'}</span></div><div><b>Email</b><span>{profile.email||'Not added'}</span></div><div><b>Phone</b><span>{profile.phone||'Not added'}</span></div><div><b>Birthday</b><span>{profile.birthday||'Not added'}</span></div><div><b>Work</b><span>{profile.work||'Not added'}</span></div><div><b>Education</b><span>{profile.education||'Not added'}</span></div></section>}
  {editing&&<div className="modal-backdrop"><section className="modal profile-editor"><div className="modal-head"><div><span>YOUR PROFILE</span><h2>Edit profile</h2></div><button onClick={()=>setEditing(false)}><X/></button></div><div className="modal-body"><label className="field"><b>Full name</b><input value={profile.name} onChange={e=>setProfile({...profile,name:e.target.value})}/></label><label className="field"><b>Username</b><input value={profile.username} onChange={e=>setProfile({...profile,username:e.target.value})}/></label><label className="field"><b>Bio</b><textarea value={profile.bio} maxLength={300} onChange={e=>setProfile({...profile,bio:e.target.value})}/></label><div className="form-grid"><label className="field"><b>City</b><input value={profile.city} onChange={e=>setProfile({...profile,city:e.target.value})}/></label><label className="field"><b>Phone</b><input value={profile.phone} onChange={e=>setProfile({...profile,phone:e.target.value})}/></label><label className="field"><b>Email</b><input type="email" value={profile.email} onChange={e=>setProfile({...profile,email:e.target.value})}/></label><label className="field"><b>Birthday</b><input type="date" value={profile.birthday} onChange={e=>setProfile({...profile,birthday:e.target.value})}/></label><label className="field"><b>Work</b><input value={profile.work} onChange={e=>setProfile({...profile,work:e.target.value})}/></label><label className="field"><b>Education</b><input value={profile.education} onChange={e=>setProfile({...profile,education:e.target.value})}/></label></div></div><div className="modal-foot"><span/><button className="primary" onClick={save}><Save size={16}/> Save profile</button></div></section></div>}
 </div>
}
